### ISSUE TITLE
Checking out Tagged Version unable to follow build docs

### ISSUE THREAD

**Issue by kbvincent** [cloudflare/cfssl#539]
We're experiencing an issue when attempting to build cfssl after checking out the 1.1.0 tag of the github repository.

Running the following commands:
```
git clone git@github.com:cloudflare/cfssl.git
git checkout tags/1.1.0
cd cfssl
export GOPATH=/.jenkins/workspace/cfssl/
go get -d ./...
go build ./cmd/...
```

We get the following output with go 1.4:
```
go/src/github.com/cloudflare/cfssl/scan/tls_handshake.go:53: undefined: tls.CipherSuites
go/src/github.com/cloudflare/cfssl/scan/tls_handshake.go:64: undefined: tls.Curves
go/src/github.com/cloudflare/cfssl/scan/tls_handshake.go:68: undefined: tls.SignatureAndHash
go/src/github.com/cloudflare/cfssl/scan/tls_handshake.go:87: undefined: tls.AllSignatureAndHashAlgorithms
go/src/github.com/cloudflare/cfssl/scan/tls_handshake.go:89: undefined: tls.SetSupportedSKXSignatureAlgorithms
go/src/github.com/cloudflare/cfssl/scan/tls_handshake.go:90: undefined: tls.ResetSupportedSKXSignatureAlgorithms
go/src/github.com/cloudflare/cfssl/scan/tls_handshake.go:93: conn.SayHello undefined (type *tls.Conn has no field or method SayHello)
go/src/github.com/cloudflare/cfssl/scan/tls_handshake.go:102: undefined: tls.Versions
go/src/github.com/cloudflare/cfssl/scan/tls_handshake.go:108: undefined: tls.CipherSuites
go/src/github.com/cloudflare/cfssl/scan/tls_handshake.go:122: undefined: tls.CipherSuites
go/src/github.com/cloudflare/cfssl/scan/tls_handshake.go:122: too many errors
```

Is there something preventing us from checking out an old branch to continue working in go1.4?

**Comment by jacobhaven** [comment]
I don't think you're setting up your `GOPATH` correctly. You need to place cfssl in the correct location (`$GOPATH/src/github.com/cloudflare/cfssl`).

Try this:
```
export GOPATH=/tmp/gopath
git clone -b 1.1.0 https://github.com/cloudflare/cfssl.git $GOPATH/src/github.com/cloudflare/cfssl
cd $GOPATH/src/github.com/cloudflare/cfssl
go get -d ./cmd/...
go build ./cmd/cfssl
```

**Comment by kbvincent** [comment]
Using the above I got the following errors:
```
signer/local/local.go:29:2: cannot find package "github.com/google/certificate-transparency/go" in any of:
	/usr/local/go/src/github.com/google/certificate-transparency/go (from $GOROOT)
	/tmp/gopath/src/github.com/google/certificate-transparency/go (from $GOPATH)
signer/local/local.go:30:2: cannot find package "github.com/google/certificate-transparency/go/client" in any of:
	/usr/local/go/src/github.com/google/certificate-transparency/go/client (from $GOROOT)
	/tmp/gopath/src/github.com/google/certificate-transparency/go/client (from $GOPATH)
ocsp/responder.go:13:2: cannot find package "github.com/jmhodges/clock" in any of:
	/usr/local/go/src/github.com/jmhodges/clock (from $GOROOT)
	/tmp/gopath/src/github.com/jmhodges/clock (from $GOPATH)
certdb/sql/database_accessor.go:11:2: cannot find package "github.com/kisielk/sqlstruct" in any of:
	/usr/local/go/src/github.com/kisielk/sqlstruct (from $GOROOT)
	/tmp/gopath/src/github.com/kisielk/sqlstruct (from $GOPATH)
certdb/dbconf/db_config.go:11:2: cannot find package "github.com/lib/pq" in any of:
	/usr/local/go/src/github.com/lib/pq (from $GOROOT)
	/tmp/gopath/src/github.com/lib/pq (from $GOPATH)
certdb/dbconf/db_config.go:12:2: cannot find package "github.com/mattn/go-sqlite3" in any of:
	/usr/local/go/src/github.com/mattn/go-sqlite3 (from $GOROOT)
	/tmp/gopath/src/github.com/mattn/go-sqlite3 (from $GOPATH)
```

**Comment by jacobhaven** [comment]
Ah, installed Go 1.4 on a test machine and figured out that the behavior of `go get` was different in Go 1.4 apparently (it updated the repo to master by default).
If you only `go get` the package you want to build, it will stay at the correct tagged commit and work around this issue.

```
git clone -b 1.1.0 https://github.com/cloudflare/cfssl.git $GOPATH/src/github.com/cloudflare/cfssl
go get github.com/cloudflare/cfssl/cmd/cfssl
$GOPATH/bin/cfssl -h
```

**Comment by kbvincent** [comment]
That worked!  Thanks for the help!
