### ISSUE TITLE
Repo specifies min go version of 1.16 to build the project, but build failed with 1.18

### ISSUE THREAD

**Issue by mitch292** [cloudflare/cfssl#1414]
Would be great to confirm the minimum version of go to build. I attempted to build with 1.18 and saw an error in a vendor package
```
Error: vendor/github.com/prometheus/common/model/metric.go:363:33: undefined: strings.CutPrefix
note: module requires Go 1.20
```
After confirming minimum version we should update the repo to reflect that. In both the go.mod and the README
